---
version: "3.8"
services:
  bas_discord_bot:
    image: p0t4t0sandwich/bas_discord_bot:latest
    container_name: bas_discord_bot
    environment:
      - TZ=UTC
      - BOT_ID=                             # The ID of the Discord bot
      - MYSQL_USER=                         # MySQL User
      - MYSQL_PASSWORD=                     # MySQL Password
      - MYSQL_HOST=                         # MySQL Host
      - MYSQL_DATABASE=                     # MySQL Database
      - TWITCH_CLIENT_ID=                   # Twitch Client ID
      - TWITCH_CLIENT_SECRET=               # Twitch Client Secret
    volumes:
      - /PATH-TO-FOLDER:/bas_discord_bot    # Path to the file storage of the bot.
    restart: unless-stopped